### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by seki-hiro** [ut-issl/tle-estimate#3]
## Overview
Reviewed the code, and discussions to make it even better.

## Detail
discuss in thread

## close condition
N/A

## Other
N/A

## Caution
N/A

**Comment by seki-hiro** [comment]
[MUST] `earth_720101_230601.bpc` and `pck00011.tpc` are also required files. So please add them to `README.md`.

**Comment by seki-hiro** [comment]
[IMO] The error message is indicating that the `np.int` method has been deprecated in NumPy, as of version 1.20. Instead, you can use the native Python int() function or specify the precision you want, e.g., `np.int64` or `np.int32`.

**Comment by seki-hiro** [comment]
[Q] When I use `batch_estimator.estimate_batch_orbit_sgp4_bstar()`, the bstar in estimated TLE is negative value. It is difficult to estimate bstar with short period GPS data, so do you recommend to use `batch_estimator.estimate_batch_orbit_sgp4()` if GPS data is limited?

Anyway, I'll try to use `batch_estimator.estimate_batch_orbit_sgp4_bstar()` if we get longer data.

**Comment by joshuacritchleymarrows** [comment]
> [Q] When I use `batch_estimator.estimate_batch_orbit_sgp4_bstar()`, the bstar in estimated TLE is negative value. It is difficult to estimate bstar with short period GPS data, so do you recommend to use `batch_estimator.estimate_batch_orbit_sgp4()` if GPS data is limited?
> 
> Anyway, I'll try to use `batch_estimator.estimate_batch_orbit_sgp4_bstar()` if we get longer data.

Yes, I think that is the best approach. I have just made a new push using estimate_batch_orbit_sgp4() instead of estimate_batch_orbit_sgp4_bstar() if the drag term goes negative.

**Comment by seki-hiro** [comment]
Thanks for the updates. It is convenient to automatically switch functions.
